"""Remove backref from Cycle.diary_entries

Revision ID: 649f90e5a3f9
Revises: f23d2708b6b2
Create Date: 2025-05-18 21:48:58.725575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649f90e5a3f9'
down_revision = 'f23d2708b6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
