"""Add cycle relationship to DiaryEntry

Revision ID: 6f15aff4ceb1
Revises: 649f90e5a3f9
Create Date: 2025-05-18 22:18:47.489233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f15aff4ceb1'
down_revision = '649f90e5a3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
