"""seed default cycles

Revision ID: b7d6ccf79f14
Revises: 02814cb27750
Create Date: 2025-05-18 21:10:44.005897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d6ccf79f14'
down_revision = '02814cb27750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
