"""filtrar ciclos somente do usuário logado

Revision ID: f1957a2728ba
Revises: b7d6ccf79f14
Create Date: 2025-05-18 21:39:12.533578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1957a2728ba'
down_revision = 'b7d6ccf79f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
