"""filtrar ciclos somente do usuário logado

Revision ID: f23d2708b6b2
Revises: f1957a2728ba
Create Date: 2025-05-18 21:44:02.212070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23d2708b6b2'
down_revision = 'f1957a2728ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
