#!/bin/bash

# CÁRIS SaaS Pro - Environment Variables Template for Render
# Este script gera um template das variáveis de ambiente necessárias

echo "🔧 CÁRIS SaaS Pro - Render Environment Variables"
echo "================================================"
echo ""
echo "Cole as seguintes variáveis no Render Dashboard:"
echo ""

# Variáveis obrigatórias
echo "# === VARIÁVEIS OBRIGATÓRIAS ==="
echo "NODE_ENV=production"
echo "POSTGRES_URL=[Será gerado automaticamente pelo Render]"
echo "NEXT_PUBLIC_APP_URL=https://caris-saas-pro.onrender.com"
echo "JWT_SECRET=$(openssl rand -hex 32)"
echo "NEXTAUTH_SECRET=$(openssl rand -hex 32)" 
echo "SESSION_SECRET=$(openssl rand -hex 32)"
echo "NEXTAUTH_URL=https://caris-saas-pro.onrender.com"
echo ""

# Variáveis opcionais mas recomendadas
echo "# === EMAIL SERVICES (Recomendado) ==="
echo "RESEND_API_KEY=sua-chave-resend"
echo "SENDGRID_API_KEY=sua-chave-sendgrid"
echo ""

echo "# === SMS NOTIFICATIONS (Opcional) ==="
echo "TWILIO_ACCOUNT_SID=seu-account-sid"
echo "TWILIO_AUTH_TOKEN=seu-auth-token"
echo "TWILIO_PHONE_NUMBER=+1234567890"
echo ""

echo "# === REAL-TIME CHAT (Opcional) ==="
echo "PUSHER_APP_ID=seu-pusher-app-id"
echo "NEXT_PUBLIC_PUSHER_KEY=sua-pusher-key"
echo "PUSHER_SECRET=seu-pusher-secret"
echo "NEXT_PUBLIC_PUSHER_CLUSTER=us2"
echo ""

echo "# === PUSH NOTIFICATIONS (Opcional) ==="
echo "VAPID_PUBLIC_KEY=sua-vapid-public-key"
echo "VAPID_PRIVATE_KEY=sua-vapid-private-key"
echo ""

echo "# === PAYMENT PROCESSING (Opcional) ==="
echo "STRIPE_SECRET_KEY=sua-stripe-secret"
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=sua-stripe-publishable"
echo "STRIPE_WEBHOOK_SECRET=sua-stripe-webhook-secret"
echo "MERCADOPAGO_ACCESS_TOKEN=seu-mercadopago-token"
echo "MERCADOPAGO_CLIENT_ID=seu-mercadopago-client-id"
echo "MERCADOPAGO_CLIENT_SECRET=seu-mercadopago-secret"
echo "NEXT_PUBLIC_MERCADOPAGO_PUBLIC_KEY=sua-mercadopago-public-key"
echo ""

echo "# === AI SERVICES (Opcional) ==="
echo "OPENAI_API_KEY=sua-openai-key"
echo "ANTHROPIC_API_KEY=sua-anthropic-key"
echo "GOOGLE_AI_API_KEY=sua-google-ai-key"
echo "GEMINI_API_KEY=sua-gemini-key"
echo ""

echo "# === ANALYTICS (Opcional) ==="
echo "GA_PROPERTY_ID=seu-ga-property-id"
echo "GA_CLIENT_EMAIL=seu-ga-client-email"
echo ""

echo "# === CLOUD STORAGE (Opcional) ==="
echo "AWS_ACCESS_KEY_ID=sua-aws-access-key"
echo "AWS_SECRET_ACCESS_KEY=sua-aws-secret-key"
echo "AWS_REGION=us-east-2"
echo "AWS_S3_BUCKET=seu-bucket"
echo ""

echo "# === FEATURE FLAGS ==="
echo "ENABLE_ANALYTICS=true"
echo "ENABLE_PUSH_NOTIFICATIONS=true"
echo "ENABLE_SMS_NOTIFICATIONS=true"
echo "ENABLE_EMAIL_NOTIFICATIONS=true"
echo "ENABLE_AI_FEATURES=true"
echo "ENABLE_PAYMENT_PROCESSING=true"
echo "ENABLE_REAL_TIME_CHAT=true"
echo ""

echo "# === APP CONFIGURATION ==="
echo "NEXT_PUBLIC_APP_NAME=Cáris SaaS Pro"
echo "NEXT_PUBLIC_APP_VERSION=1.0.0"
echo "RATE_LIMIT_REQUESTS_PER_MINUTE=100"
echo "MAX_FILE_SIZE_MB=50"
echo "ALLOWED_FILE_TYPES=pdf,doc,docx,jpg,jpeg,png,gif"
echo "SESSION_TIMEOUT_HOURS=24"
echo "REMEMBER_ME_DAYS=30"
echo "EMAIL_RATE_LIMIT_PER_HOUR=10"
echo "SMS_RATE_LIMIT_PER_HOUR=5"
echo ""

echo "================================================"
echo "✅ Template gerado com sucesso!"
echo ""
echo "📋 INSTRUÇÕES:"
echo "1. Copie as variáveis acima"
echo "2. Cole no Render Dashboard → Environment"
echo "3. Substitua 'sua-chave-*' pelos valores reais"
echo "4. Variáveis marcadas como [Opcional] podem ser adicionadas depois"
echo ""
echo "🚨 IMPORTANTE:"
echo "- POSTGRES_URL será gerado automaticamente"
echo "- JWT_SECRET, NEXTAUTH_SECRET e SESSION_SECRET foram gerados aleatoriamente"
echo "- Guarde essas chaves em local seguro"